import { createFileRoute } from "@tanstack/react-router";
import { Gem, Handshake, ShieldCheck } from "lucide-react";
import { PageHero } from "@/components/site-shell";
import { aboutImage, videoImage } from "@/lib/site-data";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "درباره ما | مبلمان اسلامی" }, { name: "description", content: "آشنایی با مسیر، ارزش‌ها و تعهد مبلمان اسلامی به اصالت و کیفیت." },
  { property: "og:title", content: "درباره مبلمان اسلامی" }, { property: "og:description", content: "روایت مجموعه‌ای متعهد به طراحی اصیل، کیفیت و همراهی مشتری." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: AboutPage });
function AboutPage() { const values = [[Gem,"اصالت","الهام از هنر و فرهنگ ایرانی در طراحی امروز."],[ShieldCheck,"کیفیت","دقت در انتخاب متریال و جزئیات ساخت."],[Handshake,"خدمات","همراهی حرفه‌ای از نخستین انتخاب تا تحویل."]] as const; return <><PageHero title="درباره مبلمان اسلامی" text="ترکیبی از تجربه، هنر و تعهد برای خلق فضاهایی ماندگار." /><section className="section-space"><div className="section-shell grid items-center gap-12 lg:grid-cols-2"><div><p className="text-sm font-bold text-gold">معرفی مجموعه</p><h2 className="mt-3 text-3xl font-bold text-primary">مبلمان، بخشی از روایت زندگی</h2><p className="mt-6 leading-8 text-muted-foreground">مجموعه مبلمان اسلامی با تمرکز بر اصالت، زیبایی و کیفیت شکل گرفته است. هدف ما فراهم کردن تجربه‌ای مطمئن و حرفه‌ای برای انتخاب مبلمانی است که سال‌ها در کنار خانواده و کسب‌وکار شما باقی بماند.</p><p className="mt-4 leading-8 text-muted-foreground">ما ریشه‌های طراحی ایرانی را با نیازهای زندگی معاصر پیوند می‌دهیم؛ بیانی آرام، کاربردی و دور از شلوغی.</p></div><img src={aboutImage} alt="کنترل کیفیت در نمایشگاه مبلمان اسلامی" width={1408} height={1104} className="aspect-[5/4] rounded-lg object-cover" /></div></section><section className="section-space bg-secondary"><div className="section-shell"><div className="grid gap-5 md:grid-cols-3">{values.map(([title,heading,text]) => { const Icon=title; return <article key={heading} className="rounded-lg bg-background p-7"><Icon className="size-9 text-gold" /><h3 className="mt-5 text-xl font-bold text-primary">{heading}</h3><p className="mt-3 leading-7 text-muted-foreground">{text}</p></article>; })}</div></div></section><section className="section-space"><div className="section-shell"><img src={videoImage} alt="فضای نمایشگاه مبلمان اسلامی" loading="lazy" width={1600} height={1008} className="max-h-[520px] w-full rounded-lg object-cover" /></div></section></>; }